src/Controllers/IdentityController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using CurrencyViewer.Models;
using CurrencyViewer.ViewModels;

namespace CurrencyViewer.Controllers
{
	public class IdentityController : Controller
	{
		private UserManager<User> _usersManager;

		private SignInManager<User> _signInManager;

		public IdentityController(UserManager<User> usersManager,
			SignInManager<User> signInManager
		)
		{
			_usersManager = usersManager;
			_signInManager = signInManager;
		}

		public IActionResult GetRegistrationPage() =>
			View("Registration");

		[HttpPost]
		public async Task<IActionResult> RegisterUser(RegistrationViewModel model)
		{
			if (!ModelState.IsValid) return View("Registration", model);

			var newUser = new User {
				Email = model.Email,
				UserName = model.Email
			};

			var registrationResult = await _usersManager.
				CreateAsync(newUser, model.Password);

			if (!registrationResult.Succeeded)
			{
				foreach (var error in registrationResult.Errors)
					ModelState.AddModelError(string.Empty, error.Description);

				return View("Registration", model);
			}

			await _signInManager.SignInAsync(newUser, isPersistent: true);

			return RedirectToAction(
				actionName: "GetCryptocurrenciesList",
				controllerName: "Home"
			);
		}

		public IActionResult GetAuthorizationView() =>
			View("Authorization");

		[HttpPost]
		public async Task<IActionResult> AuthorizeUser(AuthorizationViewModel model)
		{
			if (!ModelState.IsValid)
				return View("Authorization", model);

			var authResult = await _signInManager.
				PasswordSignInAsync(
					model.Email,
					model.Password,
					isPersistent: false,
					lockoutOnFailure: false
				);

			if (!authResult.Succeeded)
			{
				ModelState.AddModelError("", "Login or password is incorrect");
				return View("Authorization", model);
			}

			return RedirectToAction(
				controllerName: "Home",
				actionName: "GetCryptocurrenciesList"
			);
		}

		[HttpPost]
		public async Task<IActionResult> Logout()
		{
			await _signInManager.SignOutAsync();
			return RedirectToAction(nameof(GetAuthorizationView));
		}
	}
}

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset='utf-8'>
	<meta name='viewport' content='width=device-width, initial-scale=1'>
	<link rel="stylesheet" href="~/Styles/main.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://kit.fontawesome.com/9282f2e9b5.js" crossorigin="anonymous"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
		<div class="container">
			<a class="navbar-brand fs-2 fw-bold">
				Currency Viewer
			</a>
			<button class="navbar-toggler ms-5" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
				aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarContent">
				<ul class="navbar-nav me-auto"></ul>
				@if(User.Identity.IsAuthenticated)
				{
					<p class="text-cetner m-0 mt-1 d-flex mx-3">@User.Identity.Name</p>
					<form asp-action="Logout" asp-controller="Identity" method="post">
						<input type="submit" class="d-flex btn btn-secondary" value="Logout">
					</form>
				}
				else
				{
					<a class="text-center d-flex btn btn-primary" href="/Identity/GetAuthorizationView">Sign In</a>
				}
			</div>
		</div>
	</nav>
	<div class="container" style="min-height: 750px;">
		@RenderBody()
	</div>
	<div class="position-relative pt-4 mt-4 border-top text-center" style="height: 200px; bottom: 0; background: rgba(0, 0, 0, 0.5);">
		<p class="position-absolute fs-4 text-white start-50 top-50 translate-middle">
			Test web application for Fuse8.
			<a href="https://github.com/CIRCULARKA" class="link-light">Gachegov Ruslan</a>
		</p>
	</div>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@@5.0.1/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
	</script>
</body>
</html>